--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Vecnavium/PurePerms 
build-by-default: true
branches:
- stable
- master
projects:
  PurePerms:
    path: ""
    icon: icon128.png
...
